version: "3"
services:
  web:
    image: nginx
    volumes:
      - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ~/coding-tests/odeo:/var/www/html
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db
      - php
  php:
    build: .docker
    restart: always
    volumes:
      - ./.docker/conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .:/var/www/html
    links:
      - beanstalkd:beanstalkd
  composer:
    image: composer
    volumes:
      - .:/app
    command: install
    depends_on:
      - db
  db:
    image: postgres:10.14
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 32788:5432
    volumes:
      - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
  beanstalkd:
    image: placeloop/beanstalkd
    container_name: beanstalkd-server
    ports:
      - 11301:11300
    volumes:
      - ./data:/binlog
  beanstalkd-console:
    build: .docker/conf/beanstalkd-console
    restart: always
    ports:
      - "2080:2080"
  consumer:
    build: .docker/conf/consumer
    restart: always
    volumes:
      - .:/var/www/html
